### ISSUE TITLE
How you are combining the two strings ??

### ISSUE THREAD

**Issue by bharat117** [juxs/TwitterSearchKit#1]
It must be a Base64 encoded string containing the format consumerKey:ConsumerSecret.

you convert them in which format ? 
base64_consumerKey + ":" + base64_ConsumerSecret
or 
consumerKey + ":" + ConsumerSecret
then to base64

??

**Comment by juxs** [comment]
Sorry about the confusion. It should be consumerKey + ":" + consumerSecret then to base64
It's basically the base64 encoded bearer token credentials as described here https://dev.twitter.com/oauth/application-only

I'll update the readme accordingly
